FROM mdillon/postgis:10-alpine
LABEL maintainer="ZhangH <zhanghao@luokung.com>"
ARG VERSION=8.3.2

RUN apk add --no-cache \
            --virtual builddeps \
        build-base \
        curl \
        curl-dev \
        openssl-dev \
        ca-certificates \
        icu-dev && \
    apk add --no-cache libcurl && \
    curl -sfLO "https://github.com/citusdata/citus/archive/v${VERSION}.tar.gz" && \
    tar xzf "v${VERSION}.tar.gz" && \
    cd "citus-${VERSION}" && \
    ./configure && \
    make install && \
    cd .. && \
    rm -rf "citus-${VERSION}" "v${VERSION}.tar.gz" && \
    apk del builddeps

# add citus to default PostgreSQL config
RUN echo "shared_preload_libraries='citus'" >> /usr/local/share/postgresql/postgresql.conf.sample

# add scripts to run after initdb
COPY 000-configure-stats.sh 001-create-citus-extension.sql /docker-entrypoint-initdb.d/

# add health check script
COPY pg_healthcheck /

# HEALTHCHECK --interval=4s --start-period=6s CMD ./pg_healthcheck
HEALTHCHECK --interval=60s CMD ./pg_healthcheck
